sudo: required

language: sh

before_install:
    - sudo add-apt-repository ppa:jonathonf/vim -y
    - sudo apt-get update -q
    - sudo apt-get install vim -y
    - mv $TRAVIS_BUILD_DIR $HOME/.vim

script:
  - cd $HOME/.vim
  - vim --version
  - ./setup.sh
  - source ~/.bashrc
  - vim +'PlugInstall --sync' +qall

after_script:
  - vim --version

after_failure:
  - id
  - pwd
  - df -h

notifications:
  email:
    on_success: never
