sudo: required

language: sh

jobs:
  allow_failures:
    - os: linux
      dist: xenial
    - os: linux
      dist: bionic
    - os: linux
      dist: focal

before_install:
    - sudo add-apt-repository ppa:jonathonf/vim -y
    - sudo apt-get update -q
    - sudo apt-get install vim -y
    - mv $TRAVIS_BUILD_DIR $HOME/.vim

script:
  - cd $HOME/.vim
  - vim --version
  - ./setup.sh
  - source ~/.bashrc
  - vim -E -s -u $HOME/.vimrc +'PlugInstall --sync' +qall || true # fix vim E117: Unknown function: quickui#menu#reset
  - vim -E -s -u $HOME/.vimrc +'PlugInstall --sync' +qall # try PlugInstall again to verify if ok

after_script:
  - vim --version

after_failure:
  - id
  - pwd
  - df -h

notifications:
  email:
    on_success: never
